### ISSUE TITLE
ch5 VSC debug errors

### ISSUE THREAD

**Issue by elfelround** [PacktPublishing/Building-Enterprise-JavaScript-Applications#2]
downloaded chapter 5 code, installed git and init, yarn install, instaled eslint in vsc, went through eslint init
having both eslint errors and debug errors

/usr/bin/node --inspect-brk=24604 src/index.js 
Debugger listening on ws://127.0.0.1:24604/33407cc5-b0a6-45dd-9ba1-c64137380a10
Debugger attached.
/home/erick/Desktop/Building-Enterprise-JavaScript-Applications-master/Chapter05/hobnob/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Waiting for the debugger to disconnect...
SyntaxError: Unexpected token import
vm.js:80
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by d4nyll** [comment]
You need to have the [`eslint-plugin-import`](https://www.npmjs.com/package/eslint-plugin-import) package installed.

**Comment by d4nyll** [comment]
Closing due to inactivity.
